server:
  host: 0.0.0.0
  port: 3000
  mode: debug # release or debug
logger:
  log_path: logs
  log_level: debug
database:
  driver: mysql
  host: 10.90.100.35
  port: 8080
  db_name: gwadmin
  username: root
  password: admin123@
  # 数据库最大空闲连接数
  max_idel_connections: 10
  # 数据库最大打开连接数
  max_open_connections: 100
  sql_mode: true # true or false sql打印开关
validator:
  locale: zh
